"""wave1 supplier companies module

Revision ID: 20260417_0002
Revises: 20260417_0001
Create Date: 2026-04-17 14:05:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260417_0002"
down_revision = "20260417_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "company_contacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("role_label", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("verification_status", sa.String(length=32), nullable=False),
        sa.Column("source_note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("company_id", "email", name="uq_company_contact_email"),
    )
    op.create_table(
        "company_addresses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("raw_address", sa.Text(), nullable=True),
        sa.Column("normalized_address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("region", sa.String(length=128), nullable=True),
        sa.Column("postal_code", sa.String(length=32), nullable=True),
        sa.Column("country_code", sa.String(length=8), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_source_registries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("adapter_key", sa.String(length=128), nullable=False),
        sa.Column("source_layer", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_raw_ingests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("source_registry_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("ingest_status", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=255), nullable=True),
        sa.Column("trigger_mode", sa.String(length=32), nullable=False),
        sa.Column("adapter_key", sa.String(length=128), nullable=False),
        sa.Column("raw_count", sa.Integer(), nullable=False),
        sa.Column("normalized_count", sa.Integer(), nullable=False),
        sa.Column("merged_count", sa.Integer(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["requested_by_user_id"], ["users_access_users.id"]),
        sa.ForeignKeyConstraint(["source_registry_id"], ["supplier_source_registries.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "supplier_raw_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("source_registry_id", sa.String(length=36), nullable=False),
        sa.Column("ingest_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("raw_status", sa.String(length=32), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("raw_email", sa.String(length=255), nullable=True),
        sa.Column("raw_phone", sa.String(length=64), nullable=True),
        sa.Column("raw_address", sa.Text(), nullable=True),
        sa.Column("raw_capability_summary", sa.Text(), nullable=True),
        sa.Column("source_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("dedup_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("raw_payload_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ingest_id"], ["supplier_raw_ingests.id"]),
        sa.ForeignKeyConstraint(["source_registry_id"], ["supplier_source_registries.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("ingest_id", "source_fingerprint", name="uq_supplier_raw_record_ingest_fp"),
    )
    op.create_table(
        "supplier_companies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("company_id", sa.String(length=36), nullable=False),
        sa.Column("source_registry_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("supplier_status", sa.String(length=32), nullable=False),
        sa.Column("trust_level", sa.String(length=32), nullable=False),
        sa.Column("dedup_status", sa.String(length=32), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("canonical_email", sa.String(length=255), nullable=True),
        sa.Column("canonical_phone", sa.String(length=64), nullable=True),
        sa.Column("capability_summary", sa.Text(), nullable=True),
        sa.Column("capabilities_json", sa.JSON(), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("contact_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capability_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trusted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("blocked_reason", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"]),
        sa.ForeignKeyConstraint(["source_registry_id"], ["supplier_source_registries.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("company_id", name="uq_supplier_company_company"),
    )
    op.create_table(
        "supplier_sites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("supplier_company_id", sa.String(length=36), nullable=False),
        sa.Column("address_id", sa.String(length=36), nullable=True),
        sa.Column("site_name", sa.String(length=255), nullable=False),
        sa.Column("site_status", sa.String(length=32), nullable=False),
        sa.Column("trust_level", sa.String(length=32), nullable=False),
        sa.Column("capability_summary", sa.Text(), nullable=True),
        sa.Column("current_load_percent", sa.Integer(), nullable=True),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["address_id"], ["company_addresses.id"]),
        sa.ForeignKeyConstraint(["supplier_company_id"], ["supplier_companies.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_normalization_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("ingest_id", sa.String(length=36), nullable=False),
        sa.Column("raw_record_id", sa.String(length=36), nullable=False),
        sa.Column("normalized_status", sa.String(length=32), nullable=False),
        sa.Column("canonical_key", sa.String(length=255), nullable=False),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("canonical_email", sa.String(length=255), nullable=True),
        sa.Column("canonical_phone", sa.String(length=64), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=128), nullable=True),
        sa.Column("district", sa.String(length=128), nullable=True),
        sa.Column("country_code", sa.String(length=8), nullable=False),
        sa.Column("capability_summary", sa.Text(), nullable=True),
        sa.Column("capabilities_json", sa.JSON(), nullable=True),
        sa.Column("confidence_score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("dedup_fingerprint", sa.String(length=255), nullable=True),
        sa.Column("supplier_company_id", sa.String(length=36), nullable=True),
        sa.Column("normalization_payload_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ingest_id"], ["supplier_raw_ingests.id"]),
        sa.ForeignKeyConstraint(["raw_record_id"], ["supplier_raw_records.id"]),
        sa.ForeignKeyConstraint(["supplier_company_id"], ["supplier_companies.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("ingest_id", "raw_record_id", name="uq_supplier_norm_ingest_raw"),
    )
    op.create_table(
        "supplier_dedup_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("ingest_id", sa.String(length=36), nullable=False),
        sa.Column("normalization_result_id", sa.String(length=36), nullable=False),
        sa.Column("matched_supplier_company_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_status", sa.String(length=32), nullable=False),
        sa.Column("suggested_decision", sa.String(length=32), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("signals_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_reason", sa.String(length=255), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["ingest_id"], ["supplier_raw_ingests.id"]),
        sa.ForeignKeyConstraint(["matched_supplier_company_id"], ["supplier_companies.id"]),
        sa.ForeignKeyConstraint(["normalization_result_id"], ["supplier_normalization_results.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_merge_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("dedup_candidate_id", sa.String(length=36), nullable=True),
        sa.Column("normalization_result_id", sa.String(length=36), nullable=True),
        sa.Column("supplier_company_id", sa.String(length=36), nullable=False),
        sa.Column("decision_status", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("decided_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["decided_by_user_id"], ["users_access_users.id"]),
        sa.ForeignKeyConstraint(["dedup_candidate_id"], ["supplier_dedup_candidates.id"]),
        sa.ForeignKeyConstraint(["normalization_result_id"], ["supplier_normalization_results.id"]),
        sa.ForeignKeyConstraint(["supplier_company_id"], ["supplier_companies.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_verification_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("supplier_company_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_site_id", sa.String(length=36), nullable=True),
        sa.Column("verification_type", sa.String(length=64), nullable=False),
        sa.Column("previous_trust_level", sa.String(length=32), nullable=True),
        sa.Column("new_trust_level", sa.String(length=32), nullable=True),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("verified_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["supplier_company_id"], ["supplier_companies.id"]),
        sa.ForeignKeyConstraint(["supplier_site_id"], ["supplier_sites.id"]),
        sa.ForeignKeyConstraint(["verified_by_user_id"], ["users_access_users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "supplier_rating_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("supplier_company_id", sa.String(length=36), nullable=False),
        sa.Column("supplier_site_id", sa.String(length=36), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("trust_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("load_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("current_load_percent", sa.Integer(), nullable=True),
        sa.Column("source_label", sa.String(length=255), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["supplier_company_id"], ["supplier_companies.id"]),
        sa.ForeignKeyConstraint(["supplier_site_id"], ["supplier_sites.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )


def downgrade() -> None:
    op.drop_table("supplier_rating_snapshots")
    op.drop_table("supplier_verification_events")
    op.drop_table("supplier_merge_decisions")
    op.drop_table("supplier_dedup_candidates")
    op.drop_table("supplier_normalization_results")
    op.drop_table("supplier_sites")
    op.drop_table("supplier_companies")
    op.drop_table("supplier_raw_records")
    op.drop_table("supplier_raw_ingests")
    op.drop_table("supplier_source_registries")
    op.drop_table("company_addresses")
    op.drop_table("company_contacts")
